[package]
name = "projector-log-customer"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "projector-log-customer-server"
path = "src/main.rs"

[dependencies]
angzarr = { path = "../../.." }
common = { path = "../common" }
hex = "0.4"
async-trait = "0.1"
tonic = "0.12"
tonic-health = "0.12"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
prost = "0.13"

[dev-dependencies]
cucumber = "0.21"
futures = "0.3"

[[test]]
name = "cucumber"
harness = false
