apiVersion: v1
kind: ConfigMap
metadata:
  name: angzarr-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" . | nindent 4 }}
data:
  config.yaml: |
    logging:
      level: {{ .Values.logging.level }}
    grpc:
      command_port: {{ .Values.angzarr.command.port }}
      query_port: {{ .Values.angzarr.query.port }}
