[package]
name = "process-manager-order-status"
version = "0.1.0"
edition = "2021"

[features]
default = []
standalone = ["angzarr/sqlite"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "process-manager-order-status-server"
path = "src/main.rs"

[dependencies]
angzarr.workspace = true
common.workspace = true
prost.workspace = true
prost-types.workspace = true
async-trait.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
uuid.workspace = true
