[package]
name = "projector-logging"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "projector-logging-server"
path = "src/main.rs"

[dependencies]
angzarr.workspace = true
common.workspace = true
hex.workspace = true
prost.workspace = true
prost-types.workspace = true
async-trait.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
