[package]
name = "sag-order-fulfillment"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "sag-order-fulfillment-server"
path = "src/main.rs"

[dependencies]
angzarr.workspace = true
common.workspace = true
prost.workspace = true
prost-types.workspace = true
async-trait.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
cucumber.workspace = true
futures.workspace = true
uuid.workspace = true
tokio-stream.workspace = true

[[test]]
name = "acceptance"
harness = false
