[package]
name = "projector-web"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "projector-web-server"
path = "src/main.rs"

[dependencies]
angzarr.workspace = true
common.workspace = true
thiserror.workspace = true
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
sea-query.workspace = true
sea-query-binder = { version = "0.7", features = ["sqlx-postgres"] }
uuid.workspace = true
chrono = { workspace = true, features = ["serde"] }
hex.workspace = true
tokio-stream.workspace = true

[dev-dependencies]
cucumber.workspace = true
futures.workspace = true
