{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: angzarr-rb-grpc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.command }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angzarr
                port:
                  number: {{ .Values.angzarr.command.port }}
    - host: {{ .Values.ingress.hosts.query }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angzarr
                port:
                  number: {{ .Values.angzarr.query.port }}
    - host: {{ .Values.ingress.hosts.gateway }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angzarr-gateway
                port:
                  number: {{ .Values.angzarr.gateway.port }}
{{- end }}
