{{- range $name, $svc := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-{{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" $ | nindent 4 }}
    app: rb-{{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rb-{{ $name }}
  template:
    metadata:
      labels:
        app: rb-{{ $name }}
    spec:
      containers:
        - name: rb-{{ $name }}
          image: {{ $svc.image }}
          ports:
            - containerPort: {{ $svc.port }}
          env:
            - name: PORT
              value: "{{ $svc.port }}"
            - name: DOMAIN
              value: {{ $svc.domain }}
            - name: ANGZARR_ADDRESS
              value: "angzarr:{{ $.Values.angzarr.command.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: rb-{{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" $ | nindent 4 }}
spec:
  selector:
    app: rb-{{ $name }}
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
{{- end }}
