[package]
name = "player-agg-oo"
version = "0.1.0"
edition = "2021"

[dependencies]
angzarr = { path = "../../../../client/rust" }
angzarr-macros = { path = "../../../../client/rust/angzarr-macros" }
prost = "0.13"
prost-types = "0.13"
tokio = { version = "1", features = ["full"] }
