apiVersion: apps/v1
kind: Deployment
metadata:
  name: angzarr-stream
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" . | nindent 4 }}
    app: angzarr-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angzarr-stream
  template:
    metadata:
      labels:
        app: angzarr-stream
    spec:
      containers:
        - name: angzarr-stream
          image: {{ .Values.angzarr.stream.image }}
          ports:
            - containerPort: {{ .Values.angzarr.stream.port }}
          env:
            - name: ANGZARR_LOG
              value: {{ .Values.logging.level }}
            - name: GRPC_PORT
              value: "{{ .Values.angzarr.stream.port }}"
            {{- if .Values.secrets.amqpUrl }}
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: angzarr-secrets
                  key: amqp-url
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: angzarr-stream
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" . | nindent 4 }}
spec:
  selector:
    app: angzarr-stream
  ports:
    - port: {{ .Values.angzarr.stream.port }}
      targetPort: {{ .Values.angzarr.stream.port }}
