{{- if and (eq .Values.storage.type "sqlite") .Values.storage.sqlite.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "evented.fullname" . }}-data
  labels:
    {{- include "evented.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.sqlite.persistence.storageClass }}
  storageClassName: {{ .Values.storage.sqlite.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.sqlite.persistence.size }}
{{- end }}
