apiVersion: v1
kind: Service
metadata:
  name: {{ include "evented.fullname" . }}
  labels:
    {{- include "evented.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.commandPort }}
      targetPort: command
      protocol: TCP
      name: command
    - port: {{ .Values.service.queryPort }}
      targetPort: query
      protocol: TCP
      name: query
  selector:
    {{- include "evented.selectorLabels" . | nindent 4 }}
