[package]
name = "saga-cancellation"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "saga-cancellation-server"
path = "src/main.rs"

[dependencies]
angzarr = { path = "../../.." }
common = { path = "../common" }
prost = "0.13"
prost-types = "0.13"
async-trait = "0.1"
tonic = "0.12"
tonic-health = "0.12"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }

[dev-dependencies]
cucumber = "0.21"
futures = "0.3"
uuid = { version = "1", features = ["v4", "v5"] }
tokio-stream = "0.1"

[[test]]
name = "acceptance"
harness = false
