[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
angzarr.workspace = true
chrono.workspace = true
prost.workspace = true
prost-types.workspace = true
thiserror.workspace = true
uuid.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
