[package]
name = "saga-hand-table"
version = "0.1.0"
edition = "2021"

[dependencies]
angzarr-client = { workspace = true }
tokio = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
