{{- if or .Values.secrets.mongodbUri .Values.secrets.amqpUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: angzarr-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "angzarr-examples.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.mongodbUri }}
  mongodb-uri: {{ .Values.secrets.mongodbUri | quote }}
  {{- end }}
  {{- if .Values.secrets.amqpUrl }}
  amqp-url: {{ .Values.secrets.amqpUrl | quote }}
  {{- end }}
{{- end }}
