apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventstore.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eventstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.tcpPort }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "eventstore.selectorLabels" . | nindent 4 }}
