[package]
name = "projector-log-transaction"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "projector-log-transaction-server"
path = "src/main.rs"

[dependencies]
evented = { path = "../../.." }
common = { path = "../common" }
hex = "0.4"
async-trait = "0.1"
tonic = "0.12"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
