apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-projector-log-customer
  namespace: evented
  labels:
    app: go-projector-log-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-projector-log-customer
  template:
    metadata:
      labels:
        app: go-projector-log-customer
    spec:
      containers:
        - name: go-projector-log-customer
          image: go-projector-log-customer:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 50058
          env:
            - name: PORT
              value: "50058"
---
apiVersion: v1
kind: Service
metadata:
  name: go-projector-log-customer
  namespace: evented
spec:
  selector:
    app: go-projector-log-customer
  ports:
    - port: 50058
      targetPort: 50058
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-projector-log-transaction
  namespace: evented
  labels:
    app: go-projector-log-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-projector-log-transaction
  template:
    metadata:
      labels:
        app: go-projector-log-transaction
    spec:
      containers:
        - name: go-projector-log-transaction
          image: go-projector-log-transaction:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 50059
          env:
            - name: PORT
              value: "50059"
---
apiVersion: v1
kind: Service
metadata:
  name: go-projector-log-transaction
  namespace: evented
spec:
  selector:
    app: go-projector-log-transaction
  ports:
    - port: 50059
      targetPort: 50059
