apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-saga-loyalty
  namespace: angzarr
  labels:
    app: go-saga-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-saga-loyalty
  template:
    metadata:
      labels:
        app: go-saga-loyalty
    spec:
      containers:
        - name: go-saga-loyalty
          image: go-saga-loyalty:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50202
          env:
            - name: PORT
              value: "50202"
          readinessProbe:
            grpc:
              port: 50202
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 50202
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: go-saga-loyalty
  namespace: angzarr
spec:
  selector:
    app: go-saga-loyalty
  ports:
    - port: 50202
      targetPort: 50202
