apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt-saga-loyalty
  namespace: angzarr
  labels:
    app: kt-saga-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kt-saga-loyalty
  template:
    metadata:
      labels:
        app: kt-saga-loyalty
    spec:
      containers:
        - name: kt-saga-loyalty
          image: kt-saga-loyalty:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50502
          env:
            - name: PORT
              value: "50502"
          readinessProbe:
            grpc:
              port: 50502
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 50502
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kt-saga-loyalty
  namespace: angzarr
spec:
  selector:
    app: kt-saga-loyalty
  ports:
    - port: 50502
      targetPort: 50502
