apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: evented

resources:
  - namespace.yaml
  - secrets.yaml
  - evented-config.yaml
  - rabbitmq.yaml
  - redis.yaml
  - rs-customer.yaml
  - rs-transaction.yaml
  - rs-projectors.yaml
  - rs-saga-loyalty.yaml
  - go-projectors.yaml
  - py-projectors.yaml
  - evented.yaml
