apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-projector-log-customer
  namespace: evented
  labels:
    app: py-projector-log-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-projector-log-customer
  template:
    metadata:
      labels:
        app: py-projector-log-customer
    spec:
      containers:
        - name: py-projector-log-customer
          image: py-projector-log-customer:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 50060
          env:
            - name: PORT
              value: "50060"
---
apiVersion: v1
kind: Service
metadata:
  name: py-projector-log-customer
  namespace: evented
spec:
  selector:
    app: py-projector-log-customer
  ports:
    - port: 50060
      targetPort: 50060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-projector-log-transaction
  namespace: evented
  labels:
    app: py-projector-log-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-projector-log-transaction
  template:
    metadata:
      labels:
        app: py-projector-log-transaction
    spec:
      containers:
        - name: py-projector-log-transaction
          image: py-projector-log-transaction:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 50061
          env:
            - name: PORT
              value: "50061"
---
apiVersion: v1
kind: Service
metadata:
  name: py-projector-log-transaction
  namespace: evented
spec:
  selector:
    app: py-projector-log-transaction
  ports:
    - port: 50061
      targetPort: 50061
