apiVersion: apps/v1
kind: Deployment
metadata:
  name: rb-saga-loyalty
  namespace: angzarr
  labels:
    app: rb-saga-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rb-saga-loyalty
  template:
    metadata:
      labels:
        app: rb-saga-loyalty
    spec:
      containers:
        - name: rb-saga-loyalty
          image: rb-saga-loyalty:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50802
          env:
            - name: PORT
              value: "50802"
          readinessProbe:
            grpc:
              port: 50802
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 50802
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rb-saga-loyalty
  namespace: angzarr
spec:
  selector:
    app: rb-saga-loyalty
  ports:
    - port: 50802
      targetPort: 50802
