apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-customer
  namespace: evented
  labels:
    app: rs-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-customer
  template:
    metadata:
      labels:
        app: rs-customer
    spec:
      containers:
        - name: rs-customer
          image: rs-customer:latest
          ports:
            - containerPort: 50052
          env:
            - name: RUST_LOG
              value: info
            - name: PORT
              value: "50052"
---
apiVersion: v1
kind: Service
metadata:
  name: rs-customer
  namespace: evented
spec:
  selector:
    app: rs-customer
  ports:
    - port: 50052
      targetPort: 50052
