apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-saga-loyalty
  namespace: angzarr
  labels:
    app: rs-saga-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-saga-loyalty
  template:
    metadata:
      labels:
        app: rs-saga-loyalty
    spec:
      containers:
        - name: rs-saga-loyalty
          image: rs-saga-loyalty:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50102
          env:
            - name: ANGZARR_LOG
              value: info
            - name: PORT
              value: "50102"
          readinessProbe:
            grpc:
              port: 50102
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 50102
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rs-saga-loyalty
  namespace: angzarr
spec:
  selector:
    app: rs-saga-loyalty
  ports:
    - port: 50102
      targetPort: 50102
