apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-transaction
  namespace: evented
  labels:
    app: rs-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-transaction
  template:
    metadata:
      labels:
        app: rs-transaction
    spec:
      containers:
        - name: rs-transaction
          image: rs-transaction:latest
          ports:
            - containerPort: 50053
          env:
            - name: RUST_LOG
              value: info
            - name: PORT
              value: "50053"
---
apiVersion: v1
kind: Service
metadata:
  name: rs-transaction
  namespace: evented
spec:
  selector:
    app: rs-transaction
  ports:
    - port: 50053
      targetPort: 50053
