apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: angzarr
type: Opaque
stringData:
  username: guest
  password: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: angzarr
type: Opaque
stringData:
  username: angzarr
  password: angzarr
---
apiVersion: v1
kind: Secret
metadata:
  name: angzarr-secrets
  namespace: angzarr
type: Opaque
stringData:
  amqp-url: amqp://guest:guest@rabbitmq:5672
  mongodb-uri: mongodb://angzarr:angzarr@mongodb-0.mongodb-headless:27017/angzarr?authSource=admin&replicaSet=rs0&directConnection=true
