apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-saga-loyalty
  namespace: angzarr
  labels:
    app: ts-saga-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-saga-loyalty
  template:
    metadata:
      labels:
        app: ts-saga-loyalty
    spec:
      containers:
        - name: ts-saga-loyalty
          image: ts-saga-loyalty:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50402
          env:
            - name: PORT
              value: "50402"
          readinessProbe:
            grpc:
              port: 50402
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            grpc:
              port: 50402
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ts-saga-loyalty
  namespace: angzarr
spec:
  selector:
    app: ts-saga-loyalty
  ports:
    - port: 50402
      targetPort: 50402
