[package]
name = "saga-loyalty"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "saga-loyalty-server"
path = "src/main.rs"

[dependencies]
evented = { path = "../../.." }
prost = "0.13"
prost-types = "0.13"
hex = "0.4"
tonic = "0.12"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
